vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        anime_image:
            uri_prefix: /images/animes
            upload_destination: '%kernel.project_dir%/public/images/animes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
